### ISSUE TITLE
Lodash is missing in package.json

### ISSUE THREAD

**Issue by inkiltie** [cheatcode/nodejs-server-boilerplate#14]
After I run `npm install` and `npm run dev` for the first time I got bunch of `lodash` missing issues. Simple `npm install lodash` fixed it, but adding `"lodash": "^4.17.21",` to package.json would be nice.

**Comment by rglover** [comment]
Fixed in 0.10.0. I had a bunch of imports for lodash in the code but wasn't actually using any methods from it. These have been removed.
