### ISSUE TITLE
Unable to delete document after dependencies bump

### ISSUE THREAD

**Issue by inkiltie** [cheatcode/nodejs-server-boilerplate#19]
While figuring out new ApolloServer v3 and all the changes it brings after latest dependencies bump, I also found that I'm unable to delete docs anymore. I think it was working in previous versions. But anyway, turns out `await Documents.removeOne({ _id: args.documentId });` command is doing nothing in `api/documents/graphql/mutations.js`. 

`removeOne` needs to be changed to `deleteOne` to make it work: `await Documents.deleteOne({ _id: args.documentId });`

**Comment by rglover** [comment]
Thanks for the heads up! Fixed in 0.10.2.
