### ISSUE TITLE
Can not start project after take build

### ISSUE THREAD

**Issue by CagataySert** [cheatcode/nodejs-server-boilerplate#6]
Hey, after I run build script dist folder is coming out but then I tried to run start script but server can not be accesible. I do not get any specific error, it hangs until mongo connection is closed due to timeout.

By the way if I want to try run project in my local, everything works well. I got some error only in production.

Can you guys help me about it?

**Comment by rglover** [comment]
Hey @CagataySert, have you provided an external/remote MongoDB in your  `settings-prouction.json` file (at `databases.mongodb.uri`)?
